### ISSUE TITLE
Add benchmarks for the main function [Feature]

### ISSUE THREAD

**Issue by sfmig** [brainglobe/brainglobe-workflows#105]
Add a benchmark for the main function (detect+classify)

For it, try fetching larger data (larger than the test data in the repo, but not as large as a 100% realistic scenario) until the benchmarking time is reasonable:
- increase the size of the data in benchmarks gradually
- use GIN and fetch with `pooch` - [this PR](https://github.com/SainsburyWellcomeCentre/WAZP/pull/100) may be a good example to follow
- smallest dataset that is realistic is 100GB
- typically 10mins?

**Comment by adamltyson** [comment]
To test with the largest data, could these workflows not be run on our internal runner, and the data live there permanently?

**Comment by sfmig** [comment]
yes @adamltyson, that is exactly the plan. 

This issue was migrated from the `cellfinder` repo, where we initially started the benchmarking work following a "modular" approach (i.e., benchmarking individual functions, rather than a workflow). But these comments are slightly outdated now. I think the comments on the size of the data came from a discussion on how to determine what is a small/large dataset.

I will close this issue now since:
- adding a benchmark for the main function (detect+classify) is now complete (see PR #94), and
- we now know what we mean with [a small dataset](https://gin.g-node.org/BrainGlobe/test-data/src/master/cellfinder) and large dataset.

**Comment by adamltyson** [comment]
Ignore me, I got a notification about this issue (because it was transferred), and thought it was a new issue!
