### ISSUE TITLE
Refactor cellfinder workflow tests

### ISSUE THREAD

**Issue by sfmig** [brainglobe/brainglobe-workflows#26]
Suggestions for refactoring the cellfinder workflow tests, from the PR #23 review (thanks @alessandrofelder!)

- [x] Can we redefine the integration tests as parametrised instead, considering a range of input configs (default, fetching from GIN, fetching locally)?
- [x] Split the current integration tests into unit tests, each testing the individual steps (e.g., split `setup` into the 4 setup steps, and then test the actual workflow separately). This would allow us to remove the `subprocess` call and we think it would simplify the whole suite.
    - I would then use pytest's fixture caplog / capsys to assert logs
- [x] Make the tests more modular. 
   - Separate general unit tests (parser for now) and cellfinder-specific unit tests (with modules / directories)
- [x] Start a utils module for all workflows (which for now would include the parser function)
    - (unit) test this separately 
- [x] Do we need the `make_config` helper functions?
    - if we are doing away with the `subprocess` call, probably no. Instead, have a fixture that returns the config as a `CellfinderConfig` class instead.
   - if we do need them, can we make them smaller? can they be defined inside the relevant fixtures instead? 
- [x] Integrate fixtures back into file with the tests' definitions, rather than in conftest.py    
- [x] Remove `autouse=True` for `cellfinder_cache_dir` fixture: this is because `autouse=True` will automatically execute the fixture for _every_ test, and we won't want e.g. brainreg tests to trigger this fixture. (Can we have autouse only at module level?)

**Comment by alessandrofelder** [comment]
> (Can we have autouse only at module level?) 
Yes - we can define it in the module instead of `conftest.py` I think
> if an autouse fixture is defined in a test module, all its test functions automatically use it. [from `pytest` docs](https://docs.pytest.org/en/4.6.x/fixture.html#autouse-fixtures-xunit-setup-on-steroids)
