### ISSUE TITLE
Cell detection and analysis without cell classification

### ISSUE THREAD

**Issue by PedjaJJ** [brainglobe/brainglobe-workflows#47]
**Is your feature request related to a problem? Please describe.**
In current version it is not possible to get just cell detection and cell analysis without cell classification. This could be potentially beneficial if you are analyzing cFos (nuclear) staining. With parameters that can be changed in cellfinder now I was able to get very good cFos detection results. When classification is done more than half of this cells are removed. 

**Describe the solution you'd like**
I would like to see solution that will enable me to have all detected cells classified as cells and then proceed to analysis step

**Describe alternatives you've considered**
I tried changing output files (cells.xml to cell_calssifiction.xml and vice versa) but in first case he skips analysis cause no cells were detected and in the other he is running cell classification
**Additional context**

**Comment by alessandrofelder** [comment]
> support users to create their own custom workflows by using the relevant APIs?

I would agree. It would fit with our principle to prioritise Python API and napari GUIs over improvements to existing CLI tools, for one?

**Comment by adamltyson** [comment]
@PedjaJJ sorry for the delay. We're currently restructuring all of the BrainGlobe tools, and in particular making them more flexible and easier to maintain. As part of this, we're moving away from the command-line tools such as `brainmapper` (previously `cellfinder`). One reason for this is that if we support every (very sensible) request such as this, the tool becomes difficult to maintain, and breaks far more often.

If you'd like help putting together a script to achieve what you need, please let us know. However, we won't be adding this feature into the tool at this time.

**Comment by Eddymorphling** [comment]
Hi @adamltyson. I am also in the same boat where I would love to use Cellfinder for cFOS detection. From what I understand, this should be simple to implement? Any thoughts on where I can get started to modify some of the filters/classification parameters to get Cellfinder working on cFOS detection? I personally think this would be a great add-on to the existing Cellfinder/brainglobe workflows!

**Comment by adamltyson** [comment]
Hi @Eddymorphling, have you tried cell detection your data yet? I think most people have managed to use it "normally", i.e. by tweaking parameters to improve detection and then retraining as with any other data.
