### ISSUE TITLE
[BUG] Cellfinder csv output does not include all cells detected

### ISSUE THREAD

**Issue by Eddymorphling** [brainglobe/brainglobe-workflows#83]
Hi All,
I have been using `brainglobe-workflows` for a while now using a custom trained model. I noticed a small issue recently. After running the entire workflow, I see that many cells are detected as "cells" when I open the output folder using napari (screenshot below).

![image](https://github.com/brainglobe/cellfinder/assets/67712116/3bfa5c6d-adb2-495e-8886-dded08bccc77)

But when I look into the "analysis" folder that contains the `summary.csv` file I find very few cell counts in here (screenshot below). A lot of them are missing or not included. Is there a reason why this happens? My understanding is that all "cells" that I see in the napari plugin are automatically included when assigning them a brain region in the `summary.csv` file. This issue only happens in a few datasets, not all. Any advise? Thank you.

![image](https://github.com/brainglobe/cellfinder/assets/67712116/5a691fdb-3f7d-4dc7-a4ce-61e2ff19e0f8)

**Comment by Eddymorphling** [comment]
Forgot to add - I also see that a lot of points are being considered outside the atlas.

```
 INFO     2024-02-20 10:25:24 AM - INFO -  transform.py:70
                                MainProcess transform.py:70 -                   
                                Ignoring point: [2731, 252,                     
                                1546] as it falls outside the                   
                                atlas. 
```

**Comment by Eddymorphling** [comment]
The registration looks good. Its strange that the "cells" label in napari are not being considered in the final `summary.csv`. Just an FYI - I think I also noticed this recently after updating my pypi packages for brainglobe-workflows, brainreg to the latest versions.

**Comment by Eddymorphling** [comment]
Thanks @adamltyson . I am using `allen_mouse_10um` .

**Comment by alessandrofelder** [comment]
>This issue only happens in a few datasets, not all. Any advise? Thank you.

Hey @Eddymorphling - would you be able to provide the cellfinder output directories for one dataset where this happens, and one where it doesn't please?

**Comment by Eddymorphling** [comment]
Yes, of course. Here it is - [example.zip](https://github.com/brainglobe/brainglobe-workflows/files/14376560/example.zip). Thank you.

**Comment by Eddymorphling** [comment]
Just to add, I noticed in the brainglobe log files for the "no-cells" dataset that almost all cells were ignored as it falls outside the atlas. But my atlas registration looks good to be honest.

**Comment by Eddymorphling** [comment]
Sorry to bother you again , just thought of trying to setup a new env and run the analysis. Everything worked out well but when I run brainmapper - h I get the below error.
```

(brainglobe_v2) [ivm@sc1ns013is10 ~]$ brainmapper -h
Traceback (most recent call last):
  File "/home/ivm/conda/envs/brainglobe_v2/bin/brainmapper", line 5, in <module>
    from brainglobe_workflows.brainmapper.main import main
  File "/home/ivm/conda/envs/brainglobe_v2/lib/python3.10/site-packages/brainglobe_workflows/brainmapper/main.py", line 15, in <module>
    import bg_space as bgs

```
Looks like [bg-space renaming ](https://brainglobe.info/blog/bg-space-rename.html)has not been transcribed to one of the scripts. I had to pip install `bg-space` to get over the error. Also, not sure if this is related to the issue mentioned above?

**Comment by alessandrofelder** [comment]
Hey
Yes, having a look at the log file would be useful.
Visualising the points in napari makes me think this is connected to https://github.com/brainglobe/cellfinder/issues/383

Presumably there's no obvious imaging artefacts that would explain cellfinder detecting lots of cell candidates in a cuboid shape ventrally and anterior of the brain: 
![image](https://github.com/brainglobe/brainglobe-workflows/assets/10500965/cdbaebb9-984b-4160-bb8e-738d84313b76)

**Comment by Eddymorphling** [comment]
Here is the log file for the "no-cells" folder - 
[no-cells-logs.zip](https://github.com/brainglobe/brainglobe-workflows/files/14377168/no-cells-logs.zip)


 Those points from the cuboids are false artefacts from the sample holder that was used to mount the brain onto the ligthsheet. But, if you think this could pose an issue, I will implement --start-plane and --end-plane to avoid these false artefacts.

**Comment by Eddymorphling** [comment]
> Visualising the points in napari makes me think this is connected to [brainglobe/cellfinder#383](https://github.com/brainglobe/cellfinder/issues/383)

Thanks for the tip @alessandrofelder.  Just read this, so maybe I am detecting cells >65000 and that explains it? I just I will have to implement a `--start-plane` and` --end-plane` to keep it below 65000 cells for now. Is there a planned update to fix this issue?

**Comment by alessandrofelder** [comment]
> Just read this, so maybe I am detecting cells >65000 and that explains it?

Yea, I suspect so. If you wouldn't mind testing this hypothesis, you could 
`pip install git+https://github.com/brainglobe/cellfinder@switch-detection-to-uint32`
in your conda environment and then `brainmapper` again?

**Comment by Eddymorphling** [comment]
Sure, can do, thank you. I can only report back in around 24hours as it takes a day to run the cell detection on the cluster :)

**Comment by alessandrofelder** [comment]
That would be great, thank you.

**Comment by Eddymorphling** [comment]
> That would be great, thank you.

Hi @alessandrofelder Reporting half way through the run. The log files still seems to ignore a lot of points. Here is a snippet:
```

2024-02-22 11:17:57 AM - INFO - MainProcess transform.py:70 - Ignoring point: [2411, 482, 1453] as it falls outside the atlas.
2024-02-22 11:17:57 AM - INFO - MainProcess transform.py:70 - Ignoring point: [2411, 482, 1423] as it falls outside the atlas.
```
I did not run the registration again but just re-ran the cell detection/classification/analysis of running the git update that you had suggested.

**Comment by Eddymorphling** [comment]
Ah apologies. I spoke too soon. Results look good after the first dataset. I am now testing it on my other datasets that did not output the cell counts properly. Will keep you posted!

**Comment by alessandrofelder** [comment]
> Results look good after the first dataset.

:crossed_fingers: thanks - keep us posted

**Comment by Eddymorphling** [comment]
Reporting back in. Everything works like a charm now! Thank you :)

**Comment by Eddymorphling** [comment]
Just out of curiosity, was anything updated in the recent releases? My runs are way faster now, takes only around 3 -4 hours compared to 9-10hours in the past.

**Comment by adamltyson** [comment]
I spoke to @alessandrofelder and he thinks this speed up is also due to the same bug fix.

**Comment by Eddymorphling** [comment]
The best of both worlds, this is great!
